displayName=Player Interpolation
author=JarateKing
description=More responsive player movement
tags=movement,interpolation,lerp,true tile,tiles
plugins=com.playerInterpolation.PlayerInterpolationPlugin
